### PR TITLE
Add missing metadata property

### PR DESCRIPTION
**Pull request by zach-capalbo**
Closes Issue #5

### CODE REVIEW

**Comment by n-riesco** [comment]
Thank you for this contribution!

I'll test this PR tomorrow. Before I merge it, please, could you:
- [x] update [handles_v4.js](https://github.com/n-riesco/jp-kernel/blob/e2e41b4d6af487c91709d991c6f851e849e631b8/lib/handlers_v4.js#L219-L225) in the same way
- [x] add your name to the list of [AUTHORS](https://github.com/n-riesco/jp-kernel/blob/e2e41b4d6af487c91709d991c6f851e849e631b8/AUTHORS). I ask contributors to do so, to confirm their consent to distributing their contributions under the [LICENSE](https://github.com/n-riesco/jp-kernel/blob/e2e41b4d6af487c91709d991c6f851e849e631b8/LICENSE) terms.

Again, thanks for taking the time to fix this bug.

**Comment by zach-capalbo** [comment]
I've updated the repository with the requested changes

**Comment by n-riesco** [comment]
@zach-capalbo Again, thank you for doing this!

**Comment by zach-capalbo** [comment]
No problem. Thanks for all your work on this! It's pretty nifty!

**Comment by n-riesco** [comment]
Released in `jp-kernel@1.1.0`

**Pull request merged**
